output   = "models"
wipe     = true
no-tests = true

[psql]
  dbname = "DATABASE_NAME"
  host   = "DATABASE_HOST"
  port   = DATABASE_PORT
  user   = "DATABASE_USER"
  pass   = "DATABASE_PASSWORD"
  schema = "DATABASE_SCHEMA"